"""Add is_public column

Revision ID: 20e4252298ad
Revises: 
Create Date: 2025-04-28 18:55:05.663532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e4252298ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_result', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
